### ISSUE TITLE
bombs are not privat

### ISSUE THREAD

**Issue by darkfriend77** [ajuna-network/ajuna-games#16]
the 3 player bombs shouldn't be exposed to the opponent.

Since there is only one TrustedGetter to get the Board, we need to make sure that it only includes the player bombs.

With player-specific bomb storage that would have been solved, but since we only have GetBoard it seems a little bit more complicated.

**Comment by cowboy-bebug** [comment]
This is captured as part of [PLAT-320](https://ajunanetwork.atlassian.net/browse/PLAT-320).
