### ISSUE TITLE
Strange situation achieved.

### ISSUE THREAD

**Issue by darkfriend77** [ajuna-network/ajuna-games#19]
![image](https://user-images.githubusercontent.com/17710198/182934702-c5e38ddc-c23f-4cdb-be5f-4fd5127bd145.png)

Can it be that we allow moves even when the board is won?

**Comment by cowboy-bebug** [comment]
Yeah the issue was addressed in https://github.com/ajuna-network/ajuna-games/pull/18 but wasn't released.
