### ISSUE TITLE
dot4gravity: after phase changed, not able to drop stone

### ISSUE THREAD

**Issue by darkfriend77** [ajuna-network/ajuna-games#5]
after phase changed to play, not able to drop stone, even though transaction on tee get's accepted.

![image](https://user-images.githubusercontent.com/17710198/175284420-57f01e58-bce3-4e5e-a5dc-5fc3789446f8.png)

**Comment by darkfriend77** [comment]
I tried with both Alice and Bob, :-|

**Comment by andyjsbell** [comment]
@darkfriend77 Are you able to list the turns you send to help replicate this?

**Comment by andyjsbell** [comment]
Looks like this was a client side issue, closing
